name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - run: yarn ci
      - run: yarn build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PUBLISH_BRANCH: master
          publish_dir: ./storybook-static
